# Generated by Django 6.0.1 on 2026-01-13 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=20, unique=True, verbose_name='Mã lớp')),
                ('name', models.CharField(max_length=100, verbose_name='Tên lớp')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='Giảng viên')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Phòng học')),
                ('schedule', models.CharField(blank=True, max_length=200, verbose_name='Lịch học')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Danh sách lớp học',
                'ordering': ['class_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id'], 'verbose_name': 'Học viên', 'verbose_name_plural': 'Danh sách học viên'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.AddField(
            model_name='student',
            name='face_data',
            field=models.CharField(blank=True, max_length=500, verbose_name='Đường dẫn ảnh/vector đặc trưng'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã học viên'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='portal.class', verbose_name='Lớp học'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True, verbose_name='Mã buổi học')),
                ('date', models.DateField(verbose_name='Ngày học')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('topic', models.CharField(blank=True, max_length=200, verbose_name='Chủ đề buổi học')),
                ('status', models.CharField(choices=[('scheduled', 'Đã lên lịch'), ('ongoing', 'Đang diễn ra'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='scheduled', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='portal.class', verbose_name='Lớp học')),
            ],
            options={
                'verbose_name': 'Buổi học',
                'verbose_name_plural': 'Danh sách buổi học',
                'ordering': ['-date', '-start_time'],
                'unique_together': {('class_obj', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Có mặt'), ('late', 'Đi muộn'), ('absent', 'Vắng mặt'), ('excused', 'Có phép')], default='absent', max_length=10, verbose_name='Trạng thái')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='Giờ check-in')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Giờ check-out')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Độ tin cậy nhận diện (%)')),
                ('camera_id', models.CharField(blank=True, max_length=50, verbose_name='ID Camera')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='portal.student', verbose_name='Học viên')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='portal.session', verbose_name='Buổi học')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Lịch sử điểm danh',
                'ordering': ['-session__date', 'student__student_id'],
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
