# Generated by user on 2026-01-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_class_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_number',
            field=models.IntegerField(default=1, verbose_name='Buổi thứ mấy'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(
                choices=[('morning', 'Sáng'), ('afternoon', 'Chiều'), ('evening', 'Tối')],
                default='morning',
                max_length=20,
                verbose_name='Loại buổi (sáng/chiều/tối)'
            ),
        ),
    ]
